### ISSUE TITLE
V2: allBooks query with filter not working in playground

### ISSUE THREAD

**Issue by 5achinJani** [hemanth/graphql-demo#2]
![image](https://user-images.githubusercontent.com/23077544/53115859-38abc780-356d-11e9-8017-6d75dfa57b4e.png)
The query is taken from docs.
![image](https://user-images.githubusercontent.com/23077544/53115922-5ed16780-356d-11e9-810d-f022241cfc76.png)

**Comment by hemanth** [comment]
Good catch, looks like it was not migrated from `v1`

We [have it now](https://graphql-demo-v2.now.sh/).

<img width="626" alt="screen shot 2019-02-25 at 6 51 29 pm" src="https://user-images.githubusercontent.com/18315/53340213-75d9d600-392e-11e9-9af4-08a480280508.png">
